import { Money } from '../../../../shared/domain/value-objects/money';
import { BudgetStatus } from '../budget-status';
import { BudgetStateError } from '../errors/budget-state.error';
import { BudgetId } from '../value-objects/budget-id';

export interface BudgetProps {
  id: BudgetId;
  round: number;
  total: Money;
  status: BudgetStatus;
  generatedAt: Date;
  decidedAt: Date | null;
  decidedByUserId: string | null;
}

export interface GenerateBudgetInput {
  id: BudgetId;
  round: number;
  total: Money;
  generatedAt: Date;
}

export interface DecideBudgetInput {
  actorUserId: string;
  at: Date;
}

export interface RegenerateBudgetInput {
  total: Money;
  generatedAt: Date;
}

/**
 * One numbered round: what it totalled, when it was quoted, and how it was decided. Generated by
 * `WorkOrder.completeDiagnosis` / `submitSupplementaryBudget`, which compute `total` from the
 * aggregate's own items - this entity never reaches outside itself for a price (spec.md WOB-02
 * AC3).
 */
export class Budget {
  private constructor(private readonly props: BudgetProps) {}

  static generate(input: GenerateBudgetInput): Budget {
    return new Budget({
      id: input.id,
      round: input.round,
      total: input.total,
      status: BudgetStatus.Pending,
      generatedAt: input.generatedAt,
      decidedAt: null,
      decidedByUserId: null,
    });
  }

  static restore(props: BudgetProps): Budget {
    return new Budget({ ...props });
  }

  /** Resets a rejected round to `PENDING` with a fresh total, in place of opening a new round. */
  regenerate(input: RegenerateBudgetInput): void {
    this.assertStatusIs(BudgetStatus.Rejected);
    this.props.status = BudgetStatus.Pending;
    this.props.total = input.total;
    this.props.generatedAt = input.generatedAt;
    this.props.decidedAt = null;
    this.props.decidedByUserId = null;
  }

  approve(input: DecideBudgetInput): void {
    this.assertStatusIs(BudgetStatus.Pending);
    this.props.status = BudgetStatus.Approved;
    this.props.decidedAt = input.at;
    this.props.decidedByUserId = input.actorUserId;
  }

  reject(input: DecideBudgetInput): void {
    this.assertStatusIs(BudgetStatus.Pending);
    this.props.status = BudgetStatus.Rejected;
    this.props.decidedAt = input.at;
    this.props.decidedByUserId = input.actorUserId;
  }

  private assertStatusIs(expected: BudgetStatus): void {
    if (this.props.status !== expected) {
      throw new BudgetStateError(this.props.status);
    }
  }

  get id(): BudgetId {
    return this.props.id;
  }

  get round(): number {
    return this.props.round;
  }

  get total(): Money {
    return this.props.total;
  }

  get status(): BudgetStatus {
    return this.props.status;
  }

  get generatedAt(): Date {
    return this.props.generatedAt;
  }

  get decidedAt(): Date | null {
    return this.props.decidedAt;
  }

  get decidedByUserId(): string | null {
    return this.props.decidedByUserId;
  }
}
